<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCaEkfeM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCaEkfeM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCaEkfeM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCaEkfeM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCaEkfeM\App_KernelDevDebugContainer([
    'container.build_hash' => 'CaEkfeM',
    'container.build_id' => 'c2cb257a',
    'container.build_time' => 1704711380,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCaEkfeM');
