controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /home
    controller: App\Controller\HomeController::home

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\LoginController::login
    

app_security:
    path: /secure-page
    controller: App\Controller\SecurityController::index

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout