<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXf9E3CT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXf9E3CT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXf9E3CT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXf9E3CT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXf9E3CT\App_KernelDevDebugContainer([
    'container.build_hash' => 'Xf9E3CT',
    'container.build_id' => '1587f065',
    'container.build_time' => 1704815247,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXf9E3CT');
