<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBfYHXNV\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBfYHXNV/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBfYHXNV.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBfYHXNV\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBfYHXNV\App_KernelDevDebugContainer([
    'container.build_hash' => 'BfYHXNV',
    'container.build_id' => '1341b942',
    'container.build_time' => 1704375964,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBfYHXNV');
