<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYNExszQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYNExszQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYNExszQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYNExszQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYNExszQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'YNExszQ',
    'container.build_id' => 'a4534b2f',
    'container.build_time' => 1705318567,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYNExszQ');
